### ISSUE TITLE
Pull AutoComplete Options Out

### ISSUE THREAD

**Issue by ClayLewis2** [jcode999/Mind-Reader#1]
Get AutoComplete options in a workable format for the extension to use in text to speech on command.

**Comment by jcode999** [comment]
Initially, I had planned to extract auto-completion values from the PyLance language server but I have found little to no guidance on how to accomplish this or even if it is possible to achieve this.
This would be the most optimal solution and I will continue to investigate further.

Other Alternatives:
1) Capture Autocomplete directly from the current window with the assumption that we can access the contents of the drop-down menu. More research is needed. (Least probable option) 

2) Build Basic Language Server:
Use the client-server mechanism to implement language server and language server protocol for communication. 
This option is achievable and well-documented. Using this approach we will have finer control over the suggestion compared to using secondary langugage server. 
Although using this approach we can achieve autocomplete function, send completion options to both vscode and voice control system, the process of building the language server could potentially be painstaking and time intensive. 

More on this here: https://code.visualstudio.com/api/language-extensions/language-server-extension-guide

**Comment by jcode999** [comment]
use this inbuilt function to collect IntelliSense autocomplete options:
"vscode.commands.executeCommand<vscode.CompletionList[]>(
		'vscode.executeCompletionItemProvider',
		activeEditor.document.uri,
		activeEditor.selection.active,)
install pylance (recommended) or another python language server.

**Comment by jcode999** [comment]
error while trying to access completion items: 
items Property 'items' does not exist on type 'CompletionList<CompletionItem>[]
The code editor displays this error even though items Property is defined in class CompletionList
Ran and Debugged the code, runs fine without issue. 
<img width="1440" alt="Screenshot 2022-11-28 at 1 49 32 PM" src="https://user-images.githubusercontent.com/54523368/204368884-d0ba57c6-ff55-4512-99c2-1938c882ebe5.png">
<img width="1440" alt="Screenshot 2022-11-28 at 1 53 52 PM" src="https://user-images.githubusercontent.com/54523368/204368928-6f0acf46-6140-4049-91a2-d23d7feeb964.png">

**Comment by jcode999** [comment]
The issue of pulling out the auto-complete texts from the language server is completed. 
@hj131 I have put some to-do's in the comment section, please go over them and complete the rest.
